version: '3.8'

services:
  rag_api:
    build: .
    container_name: rag_api
    command: ["uvicorn", "rag_api.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
      - neo4j
      - weaviate
      - minio
    networks:
      - rag_net

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: dme_user
      POSTGRES_PASSWORD: dme_pass
      POSTGRES_DB: dme_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - rag_net

  neo4j:
    image: neo4j:5-community
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/test
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4jdata:/data
    networks:
      - rag_net

  weaviate:
    image: semitechnologies/weaviate:1.24.8
    container_name: weaviate
    restart: always
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
    ports:
      - "8080:8080"
    volumes:
      - weaviatedata:/var/lib/weaviate
    networks:
      - rag_net

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - miniodata:/data
    networks:
      - rag_net

volumes:
  pgdata:
  neo4jdata:
  weaviatedata:
  miniodata:

networks:
  rag_net:
    driver: bridge 