name: Build DME Knowledge Base

on:
  schedule:
    # Run daily at 03:00 UTC (night-time in US)
    - cron: '0 3 * * *'
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-kb:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed to commit back changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Poetry
        run: pip install poetry
      
      - name: Install dependencies
        run: poetry install --no-interaction --no-root
      
      - name: Lint with ruff
        run: poetry run ruff .
      
      - name: Run SQLite to KB update
        run: poetry run python indexer/kb_update.py
      
      - name: Commit updated KB file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add master_kb.json
          git diff --quiet && git diff --staged --quiet || git commit -m "Update knowledge base - $(date +'%Y-%m-%d')"
          git push origin HEAD:main
          
      - name: Run embedding and vector upload
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          PINECONE_ENVIRONMENT: ${{ secrets.PINECONE_ENVIRONMENT }}
          PINECONE_INDEX_NAME: ${{ secrets.PINECONE_INDEX_NAME }}
          # Typesense is optional, so these may not be set
          TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
          TYPESENSE_HOST: ${{ secrets.TYPESENSE_HOST }}
          TYPESENSE_PORT: ${{ secrets.TYPESENSE_PORT }}
          TYPESENSE_PROTOCOL: ${{ secrets.TYPESENSE_PROTOCOL }}
        run: poetry run python indexer/embed_upsert.py
        
      - name: Create log artifact
        run: |
          mkdir -p logs
          echo "KB update completed at $(date)" > logs/kb_update.log
          echo "Embedding and vector upload completed at $(date)" > logs/embed_upsert.log
          
      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kb-build-logs
          path: logs/
      
      - name: Send notification
        if: success()
        env:
          SLACK_HOOK: ${{ secrets.SLACK_HOOK }}
        run: |
          if [ -n "$SLACK_HOOK" ]; then
            MESSAGE="DME KB update complete. Knowledge base updated and vectors uploaded to Pinecone."
            curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"$MESSAGE\"}" "$SLACK_HOOK"
          fi
      
      - name: Report completion status
        if: success()
        run: echo "Knowledge base build complete and vectors uploaded to Pinecone!" 