name: Daily DME Sync

on:
  schedule:
    # Run at 02:00 AM New York time (America/New_York)
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This is needed for push access
      actions: write   # This is needed to trigger workflows
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run sync script
        run: python dme_sync.py
        
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dme.db
          
          # Only commit if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update database - $(date +'%Y-%m-%d')"
            
            # Pull latest changes with rebase strategy to avoid merge commits
            git pull --rebase origin main
            
            # Push changes
            git push origin HEAD:main
          fi
      
      # Optional Discord/Slack notification
      - name: Send notification
        if: success()
        env:
          WEBHOOK_URL: ${{ secrets.NOTIFICATION_WEBHOOK_URL }}
        run: |
          if [[ -n "$WEBHOOK_URL" ]]; then
            # Check if there were changes
            if git diff --name-only HEAD HEAD~1 | grep -q "dme.db"; then
              COUNT=$(sqlite3 dme.db "SELECT COUNT(*) FROM items")
              MESSAGE="DME Sync completed successfully. Database now contains $COUNT items."
            else
              MESSAGE="DME Sync completed successfully. No changes detected."
            fi
            
            # For Discord
            if [[ "$WEBHOOK_URL" == *"discord.com"* ]]; then
              curl -H "Content-Type: application/json" -d "{\"content\":\"$MESSAGE\"}" "$WEBHOOK_URL"
            # For Slack
            elif [[ "$WEBHOOK_URL" == *"slack.com"* ]]; then
              curl -H "Content-Type: application/json" -d "{\"text\":\"$MESSAGE\"}" "$WEBHOOK_URL"
            fi
          fi
      
      # Trigger Knowledge Base update workflow using workflow_dispatch event
      - name: Trigger KB Build
        if: success()
        uses: actions/github-script@v6
        with:
          # Use repository PAT instead of GITHUB_TOKEN for cross-workflow permissions
          github-token: ${{ secrets.WORKFLOW_PAT }}
          script: |
            try {
              console.log('Triggering build-kb.yml workflow...');
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'build-kb.yml',
                ref: 'main'
              });
              console.log('Successfully triggered build-kb.yml workflow');
            } catch (error) {
              console.error('Error triggering workflow:', error);
              core.setFailed(`Failed to trigger workflow: ${error.message}`);
            } 